games/urls.py
from django.urls import path

from .views import MathFactsView, AnagramHuntView, save_score

app_name = 'games'
urlpatterns = [
    path('math-facts/', MathFactsView.as_view(), name='math-facts'),
    path('anagram-hunt/', AnagramHuntView.as_view(), name='anagram-hunt'),
    path('save_score/', save_score, name='save_score'),
]

play2learn/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("account/", include("allauth.urls")),
    path('', include("games.urls")),
    path('users/', include('users.urls', namespace='users')),
    path('', views.home_view, name='home'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('myaccount/', views.my_account_view, name='my_account'),
]

games/models.py
from django.conf import settings
from django.db import models

class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    game = models.CharField(max_length=200)
    score = models.IntegerField()

class GameRecord(models.Model):
    GAME_CHOICES = [
        ('MathGame', 'Math Facts Practice'),
        ('AnagramGame', 'Anagram Hunt'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_finished = models.DateTimeField(auto_now_add=True)
    game_type = models.CharField(max_length=200, choices=GAME_CHOICES)
    game_settings = models.JSONField(default=dict)
    final_score = models.IntegerField()
# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields

class CustomUserAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name']

games/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import JsonResponse
from .models import GameRecord
import json

class MathFactsView(TemplateView):
    template_name = "math-facts.html"

class AnagramHuntView(TemplateView):
    template_name = "anagram-hunt.html"

def save_score(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        user = request.user
        game_type = data.get('game_type')
        game_settings = json.loads(data.get('game_settings'))
        final_score = data.get('final_score')

     #some input validation here?  
        
        if not game_type or not isinstance(game_type, str):
            return JsonResponse({'error': 'Invalid game_type'}, status=400)

        if not game_settings or not isinstance(game_settings, dict):
            return JsonResponse({'error': 'Invalid game_settings'}, status=400)

        if not final_score or not isinstance(final_score, int):
            return JsonResponse({'error': 'Invalid final_score'}, status=400) 

        GameRecord.objects.create(
            user=user,
            game_type=game_type,
            game_settings=game_settings,
            final_score=final_score,
        )

        return JsonResponse({'message': 'success'})
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)
    
def leaderboard(request, game_type):
    top_scores = GameRecord.objects.filter(game_type=game_type).order_by('-final_score')[:10]
    top_scores_list = list(top_scores.values('user__username', 'final_score'))

    return JsonResponse(top_scores_list, safe=False)

play2learn/views.py
from django.shortcuts import render

def my_account_view(request):
    # Add any additional context data you need
    context = {}
    return render(request, 'account/myaccount.html', context)

def home_view(request):
    # Add any additional context data you need
    context = {}
    return render(request, 'home.html', context)

users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserAuthenticationForm, CustomUserChangeForm
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.decorators import login_required
from games.models import GameRecord

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            backend = 'django.contrib.auth.backends.ModelBackend'
            user.backend = backend
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'account/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = CustomUserAuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = CustomUserAuthenticationForm()
    return render(request, 'account/login.html', {'form': form})

@login_required
def my_account_view(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = CustomUserChangeForm(instance=request.user)
    
    tracking_history = GameRecord.objects.filter(user=request.user)
    leaderboard_AnagramGame = GameRecord.objects.filter(game_type='AnagramGame').order_by('-final_score')
    leaderboard_MathGame = GameRecord.objects.filter(game_type='MathGame').order_by('-final_score')

    print(leaderboard_MathGame)

    context = {
        'form': form,
        'tracking_history': tracking_history,
        'leaderboard_AnagramGame': leaderboard_AnagramGame,
        'leaderboard_MathGame': leaderboard_MathGame,
    }
    return render(request, 'account/myaccount.html', context)

templates/_base_vue.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<!-- Bootstrap CSS CDN-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Play2Learn</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:my_account' %}">My Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games:anagram-hunt' %}">Anagram Hunt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games:math-facts' %}">Math Facts Practice</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

  {% block main %}{% endblock %}
  <div id="app"></div>
  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/anagram-hunt.html
{% extends "_base_vue.html" %}

{% block title %}Anagram Hunt{% endblock %}
{% block main %}
  <h1>Anagram Hunt</h1>
  {{ block.super }}
{% endblock %} 

templates/home.html
{% extends '_base_vue.html' %}

{% block title %}Home{% endblock %}

{% block main %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Welcome to Play2Learn!</h1>
        <hr class="my-4">
       
    </div>
</div>
{% endblock %}

templates/math-facts.html
{% extends "_base_vue.html" %}

{% block title %}Math Facts{% endblock %}
{% block main %}
  <h1>Math Facts</h1>
  {{ block.super }}
{% endblock %}